### PR TITLE
Add Seed Creation system and tests

### LINKED ISSUE #66: Seed system part 2
Creating a seed system creation for addresses and finish the api implementation

### PR DESCRIPTION
**Pull request by 0xdieman**
- Modifying the fragment managing system for it not to create a new fragment each time
- Adding a create seed activity which saves a 5 words seed
- Adding a lot of tests
Closes #66

### CODE REVIEW

**Review by vfaltings — APPROVED** [review]
Looks good to me, the FragmentManager makes the MainActivity way cleaner nice job on that.

**Comment by 0xdieman** [comment]
> 

You're talking about the test ? But yeah, the testing part for the fragment is not optimal as there is a lot of state involved, so I could not test everything I wanted to.

**Comment by 0xdieman** [comment]
Also I should mention that the seed words are just taken from a random word list I created but we will add a real english words list later.

**Comment by ahominal** [comment]
> @ahominal You're talking about the test ? But yeah, the testing part for the fragment is not optimal as there is a lot of state involved, so I could not test everything I wanted to.

All right! I'll use what  you've done to test the rest then !

**Pull request merged**
