### PR TITLE
Loginscreen

### PR DESCRIPTION
**Pull request by vfaltings**
Login screen feature.

Users can enter a username and password and attempt to login. For the moment on successful login they are sent to the Greeting Activity. If they input incorrect credentials they are given feedback in the form of alerts.

### CODE REVIEW

**Review by Zotchh — APPROVED** [review]
I think local.properties shouldn't be tracked by github

**Comment by 0xdieman** [comment]
I guess the `nextActivity` function is not well named for its utility and `tooManyAttemptsError` having an `Intent` parameter which will always be of the same type is not optimal but I think this is because of the lack of knowledge concerning the future activities that will be launched when logged in or when failing to. 

Also maybe `authCredentials` could rather respond with a preciser type than a boolean, maybe an enum thing that would represent different authentication errors ? (for later)

Just trying to be constructive on those shiny pull requests

**Review by 0xdieman — APPROVED** [review]
I guess the `nextActivity` function is not well named for its utility and `tooManyAttemptsError` having an `Intent` parameter which will always be of the same type is not optimal but I think this is because of the lack of knowledge concerning the future activities that will be launched when logged in or when failing to.

Also maybe `authCredentials` could rather respond with a preciser type than a boolean, maybe an enum thing that would represent different authentication errors ? (for later)

Just trying to be constructive on those shiny pull requests

**Comment by vfaltings** [comment]
Yeah for sure, the idea with `nextActivity` would just be to simplify the refactoring once we have the login screen going to the profile instead of the Greeting Activity. Good idea on the enum for `authCredentials` we can make the switch once we integrate with the profile model (so that we either return success with the new User object or a failure)

**Pull request merged**
