### PR TITLE
User shared and cached DB + some bug correction

### PR DESCRIPTION
**Pull request by ahominal**
- Update of profile fragment to display some of users data (to be updated in the future with main screen)
- Added some test and modified buttons on home fragment to go on related activities while clicking
- Creation of global shared user database that caches user's who logged in with this instance of the application

### CODE REVIEW

**Comment by vfaltings** [comment]
Also is there any way to have avoid setOnClickListener for the buttons of the main screen (like we had it set up before)

**Review by vfaltings — APPROVED** [review]
Looks good otherwise

**Comment by Zotchh** [comment]
> Also is there any way to have avoid setOnClickListener for the buttons of the main screen (like we had it set up before)

I'm not sure to understand, there is no setOnClickListener in the MainActivity

**Comment by Zotchh** [comment]
Ah nevermind @vfaltings I think I saw what you were talking about. if it's about the onClickListener in the HomeFragment then it's better to have it this way.

This quick video explain it well: https://www.youtube.com/watch?v=cMVlhTT9fL4
but basically it's better to use setOnClickListener especially when working with fragments

**Review by Zotchh — APPROVED** [review]
It's good to have moved the btn in MainActivity to the HomeFragment, it makes more sense and overall I agree with @vfaltings about the enum

**Pull request merged**
